# This is a basic workflow to help you get started with Actions

name: Build App

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install NodeJS
      run: | 
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt install nodejs

    - name: Install Yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash

    - name: Update Packages
      run: |
        cd donatespot
        npm install
        npm update
        yarn install
    - name: Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github_bot@mail.com"
        git add --all
        git diff --quiet && git diff --staged --quiet || git commit -am 'Updating changes'
        git push
