name: Build App

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      run: | 
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt install nodejs

    - name: Install Yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash

    - name: Update Packages
      run: |
        cd donatespot
        rm yarn.lock
        npm install
        npm update
        yarn install
        yarn upgrade

    - name: Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github_bot@mail.com"
        git add --all
        git diff --quiet && git diff --staged --quiet || git commit -am 'Updating changes'
        git push
