name: Build App

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      run: | 
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
        sudo apt install nodejs

    - name: Update Packages
      run: |
        cd donatespot
        npm install
        npm update